title:             한 개발자의 기술 블로그
email:             elaijh84@daum.net
description:       매일 공부한 것을 기록하는 습관을 만들기 위한 블로그입니다. 
author:            BYC
baseurl:           
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  
github_username:   byoungyong
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
